import { defaultDashboardFilters } from "./constants";
import type { DashboardData } from "./types";

export const mockDashboardData: DashboardData = {
  stats: [
    {
      key: "totalFamilies",
      label: "Total Keluarga",
      value: "50",
      caption: "Keluarga aktif",
      iconKey: "families",
    },
    {
      key: "averageScore",
      label: "Avg Score",
      value: "74.5",
      caption: "Rata-rata umum",
      iconKey: "average",
    },
    {
      key: "berlian",
      label: "Berlian",
      value: "5",
      caption: "Tier tertinggi",
      iconKey: "berlian",
    },
    {
      key: "emas",
      label: "Emas",
      value: "20",
      caption: "Stabil bertumbuh",
      iconKey: "emas",
    },
    {
      key: "perak",
      label: "Perak",
      value: "15",
      caption: "Butuh penguatan",
      iconKey: "perak",
    },
  ],
  tierDistribution: [
    { tier: "Berlian", value: 10 },
    { tier: "Emas", value: 40 },
    { tier: "Perak", value: 30 },
    { tier: "Perunggu", value: 15 },
    { tier: "Merah", value: 5 },
  ],
  dimensionScores: [
    { label: "Ad-Din", value: 82 },
    { label: "An-Nasl", value: 78 },
    { label: "Al-Mal", value: 68 },
    { label: "An-Nafs", value: 75 },
    { label: "Al-Aql", value: 70 },
  ],
  monthlyTrend: [
    { month: "2026-01", label: "Jan", value: 65 },
    { month: "2026-02", label: "Feb", value: 70 },
    { month: "2026-03", label: "Mar", value: 75 },
    { month: "2026-04", label: "Apr", value: 75 },
    { month: "2026-05", label: "Mei", value: 80 },
    { month: "2026-06", label: "Jun", value: 80 },
  ],
  unitPerformanceRows: [
    {
      unitId: "unit-a",
      unitName: "Unit A",
      families: 15,
      average: 82,
      religion: 85,
      economy: 78,
    },
    {
      unitId: "unit-b",
      unitName: "Unit B",
      families: 12,
      average: 76,
      religion: 80,
      economy: 72,
    },
    {
      unitId: "unit-c",
      unitName: "Unit C",
      families: 10,
      average: 71,
      religion: 75,
      economy: 68,
    },
    {
      unitId: "unit-d",
      unitName: "Unit D",
      families: 8,
      average: 65,
      religion: 70,
      economy: 60,
    },
  ],
  familyScoreRows: [
    {
      id: "family-a",
      name: "Bpk A",
      unitName: "A",
      date: "Apr",
      score: 88,
      tier: "Berlian",
      adDin: 92,
      alMal: 85,
    },
    {
      id: "family-b",
      name: "Bpk B",
      unitName: "A",
      date: "Apr",
      score: 76,
      tier: "Emas",
      adDin: 80,
      alMal: 72,
    },
    {
      id: "family-c",
      name: "Bpk C",
      unitName: "B",
      date: "Apr",
      score: 68,
      tier: "Perak",
      adDin: 75,
      alMal: 65,
    },
    {
      id: "family-d",
      name: "Bpk D",
      unitName: "D",
      date: "Apr",
      score: 59,
      tier: "Merah",
      adDin: 62,
      alMal: 55,
    },
  ],
  focusDimensions: [
    { label: "Al-Mal", value: 15 },
    { label: "Al-Aql", value: 12 },
    { label: "An-Nafs", value: 8 },
  ],
  filters: defaultDashboardFilters,
  filterOptions: [
    { label: "Unit BMT", value: "Semua unit" },
    { label: "Tier", value: "Semua tier" },
    { label: "Tanggal", value: "Apr 2026" },
  ],
  updatedAt: "2026-05-26T08:00:00.000Z",
};
