import type { AssessmentParticipant, AssessmentResult } from "./types";

export const assessmentParticipants: AssessmentParticipant[] = [
  {
    kepala_keluarga: "Bapak Ahmad",
    nama_istri: "Ibu Siti",
    alamat: "RT 01/RW 04, Desa Mawar",
    phone: "6281211112222",
    jml_anggota: "4",
    instansi_id: "1",
    instansi_name: "Unit BMT A",
  },
  {
    kepala_keluarga: "Bapak Rahmat",
    nama_istri: "Ibu Aminah",
    alamat: "RT 03/RW 02, Desa Melati",
    phone: "628122223333",
    jml_anggota: "5",
    instansi_id: "2",
    instansi_name: "Unit BMT B",
  },
];

export const assessmentResults: AssessmentResult[] = [
  {
    id: "assessment-001",
    kepala_keluarga: "Bapak Ahmad",
    nama_istri: "Ibu Siti",
    alamat: "RT 01/RW 04, Desa Mawar",
    phone: "6281211112222",
    instansi_name: "Unit BMT A",
    source: "Link Form",
    submittedAt: "2026-06-08",
    answers: [
      { questionId: "q8", score: 20 },
      { questionId: "q9", score: 16 },
      { questionId: "q10", score: 12 },
      { questionId: "q11", score: 15 },
      { questionId: "q12", score: 12 },
      { questionId: "q13", score: 8 },
      { questionId: "q14", score: 20 },
      { questionId: "q15", score: 12 },
      { questionId: "q16", score: 15 },
      { questionId: "q17", score: 12 },
      { questionId: "q18", score: 16 },
      { questionId: "q19", score: 15 },
      { questionId: "q20", score: 15 },
      { questionId: "q21", score: 12 },
      { questionId: "q22", score: 8 },
      { questionId: "q23", score: 12 },
      { questionId: "q24", score: 15 },
      { questionId: "q25", score: 8 },
      { questionId: "q26", score: 8 },
      { questionId: "q27", score: 15 },
      { questionId: "q28", score: 15 },
      { questionId: "q29", score: 12 },
      { questionId: "q30", score: 12 },
      { questionId: "q31", score: 15 },
      { questionId: "q32", score: 12 },
      { questionId: "q33", score: 8 },
      { questionId: "q34", score: 20 },
      { questionId: "q35", score: 16 },
      { questionId: "q36", score: 12 },
      { questionId: "q37", score: 12 },
      { questionId: "q38", score: 15 },
      { questionId: "q39", score: 8 },
    ],
  },
  {
    id: "assessment-002",
    kepala_keluarga: "Bapak Rahmat",
    nama_istri: "Ibu Aminah",
    alamat: "RT 03/RW 02, Desa Melati",
    phone: "628122223333",
    instansi_name: "Unit BMT B",
    source: "Chat Bot Whatsapp",
    submittedAt: "2026-06-09",
    answers: [
      { questionId: "q8", score: 12 },
      { questionId: "q9", score: 12 },
      { questionId: "q10", score: 8 },
      { questionId: "q11", score: 8 },
      { questionId: "q12", score: 4 },
      { questionId: "q13", score: 4 },
      { questionId: "q14", score: 16 },
      { questionId: "q15", score: 8 },
      { questionId: "q16", score: 12 },
      { questionId: "q17", score: 8 },
      { questionId: "q18", score: 12 },
      { questionId: "q19", score: 12 },
      { questionId: "q20", score: 12 },
      { questionId: "q21", score: 8 },
      { questionId: "q22", score: 8 },
      { questionId: "q23", score: 8 },
      { questionId: "q24", score: 12 },
      { questionId: "q25", score: 8 },
      { questionId: "q26", score: 6 },
      { questionId: "q27", score: 12 },
      { questionId: "q28", score: 12 },
      { questionId: "q29", score: 8 },
      { questionId: "q30", score: 8 },
      { questionId: "q31", score: 12 },
      { questionId: "q32", score: 8 },
      { questionId: "q33", score: 6 },
      { questionId: "q34", score: 16 },
      { questionId: "q35", score: 12 },
      { questionId: "q36", score: 8 },
      { questionId: "q37", score: 8 },
      { questionId: "q38", score: 12 },
      { questionId: "q39", score: 6 },
    ],
  },
];
