import type { AnggotaBmt } from "./types";

export const mockAnggotaBmtRows: AnggotaBmt[] = [
  {
    id: "keluarga-001",
    kepala_keluarga: "Bapak Ahmad",
    nama_istri: "Ibu Siti",
    address: "RT 01/RW 04, Desa Mawar",
    kecamatan: "Cakung",
    kabupaten: "Kota Jakarta Timur",
    provinsi: "DKI Jakarta",
    phone: "6281211112222",
    jml_anggota: 4,
    instansi_id: 1,
    instansi_name: "Unit BMT A",
    is_delete_keluarga: false,
    created_at: "2026-05-25T08:00:00.000Z",
    created_by: "mock",
  },
  {
    id: "keluarga-002",
    kepala_keluarga: "Bapak Rahmat",
    nama_istri: "Ibu Aminah",
    address: "RT 03/RW 02, Desa Melati",
    kecamatan: "Bekasi Timur",
    kabupaten: "Kota Bekasi",
    provinsi: "Jawa Barat",
    phone: "6281222223333",
    jml_anggota: 3,
    instansi_id: 2,
    instansi_name: "Unit BMT B",
    is_delete_keluarga: false,
    created_at: "2026-05-24T08:00:00.000Z",
    created_by: "mock",
  },
  {
    id: "keluarga-003",
    kepala_keluarga: "Bapak Hasan",
    nama_istri: "Ibu Nur",
    address: "RT 05/RW 01, Desa Anggrek",
    kecamatan: "Pancoran Mas",
    kabupaten: "Kota Depok",
    provinsi: "Jawa Barat",
    phone: "6281233334444",
    jml_anggota: 7,
    instansi_id: 3,
    instansi_name: "Unit BMT C",
    is_delete_keluarga: false,
    created_at: "2026-05-23T08:00:00.000Z",
    created_by: "mock",
  },
];
